# Generated by Django 4.0 on 2021-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
