# Generated by Django 4.0 on 2021-12-24 11:11

import computing_environment.models.job
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0006_job_created_at_job_state_job_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='program',
            field=models.FileField(upload_to=computing_environment.models.job.program_save_directory),
        ),
    ]
