# Generated by Django 4.0 on 2021-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0008_alter_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_worker_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
