# Generated by Django 4.0 on 2021-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0011_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='python', max_length=63),
            preserve_default=False,
        ),
    ]
