# Generated by Django 4.0 on 2021-12-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0013_job_memory_usage_job_processor_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='memory_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='processor_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
