# Generated by Django 4.0.1 on 2022-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0014_alter_job_memory_usage_alter_job_processor_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='jobresult',
            name='avg_memory_usage',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobresult',
            name='avg_processor_usage',
            field=models.DecimalField(decimal_places=2, default=54, max_digits=5),
            preserve_default=False,
        ),
    ]
