# Generated by Django 4.0.1 on 2022-01-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0015_alter_job_options_jobresult_avg_memory_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='computing_environment.job'),
        ),
    ]
