# Generated by Django 4.0.1 on 2022-01-08 18:27

import computing_environment.models.job
import computing_environment.models.job_result
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0016_alter_jobresult_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AlterField(
            model_name='job',
            name='program',
            field=models.FileField(upload_to=computing_environment.models.job.program_save_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='job',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobresult',
            name='result',
            field=models.FileField(upload_to=computing_environment.models.job_result.result_save_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])]),
        ),
    ]
