# Generated by Django 4.0.1 on 2022-01-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0018_worker_jobresult_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobResult',
            new_name='SubJob',
        ),
    ]
