# Generated by Django 4.0.1 on 2022-01-15 10:02

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0019_rename_jobresult_subjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_worker_call',
        ),
        migrations.RemoveField(
            model_name='job',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='processor_usage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='settings',
        ),
        migrations.AddField(
            model_name='subjob',
            name='last_worker_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjob',
            name='memory_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjob',
            name='processor_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjob',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subjob',
            name='state',
            field=django_fsm.FSMField(default='available', max_length=50, protected=True),
        ),
    ]
