# Generated by Django 4.0.1 on 2022-01-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0020_remove_job_last_worker_call_remove_job_memory_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjob',
            name='avg_memory_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='subjob',
            name='avg_processor_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
