# Generated by Django 4.0.1 on 2022-01-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0021_alter_subjob_avg_memory_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='processor',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='ram',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
