# Generated by Django 4.0 on 2022-01-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0022_alter_worker_processor_alter_worker_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_jobs', to='computing_environment.job'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='ram',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
