# Generated by Django 4.0 on 2022-01-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0023_alter_subjob_job_alter_worker_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ip_address',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
