# Generated by Django 4.0.1 on 2022-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0025_alter_worker_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjob',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
