# Generated by Django 4.0.1 on 2022-01-22 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing_environment', '0026_subjob_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worked_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
